# Generated by Django 4.2.4 on 2023-09-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_random_pwd_credenciales_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactarnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='user123@hotmail.com', max_length=50)),
                ('numero', models.IntegerField(default=0)),
                ('mensaje', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='user123@hotmail.com', max_length=150)),
                ('port', models.IntegerField(default=5432, max_length=4)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='user123@hotmail.com', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Credenciales',
        ),
        migrations.RemoveField(
            model_name='random_pwd',
            name='usuario',
        ),
    ]
