# Generated by Django 4.2.4 on 2023-09-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_contactarnos_credenciales_db_credenciales_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales_db',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='credenciales_p',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
