# Generated by Django 4.2.4 on 2023-09-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_credenciales_db_usuario_credenciales_p_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales_db',
            name='db_name',
            field=models.CharField(default='postgres', max_length=50),
        ),
    ]
