# Generated by Django 4.2.4 on 2023-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_credenciales_db_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciales_p',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
    ]
